Repository Qihoo360/wayne, pull requests merged in 2018-11, with the labels that each got.

#6 frontend: fix init namespace error
  src/frontend/package-lock.json
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.ts
Labels: kind/bug, sig/frontend

#23 Create LICENSE
  LICENSE
Labels: kind/documentation, lgtm

#26 frontend: fix admin reportform dateformat error
  src/frontend/package.json
  src/frontend/src/app/admin/reportform/deploy/deploy.component.html
  src/frontend/src/app/admin/reportform/deploy/deploy.component.ts
Labels: kind/bug, sig/frontend

#27 frontend: 添加创建部署资源单位,样式调整
  src/frontend/src/app/portal/deployment/create-edit-deployment/create-edit-deployment.component.html
  src/frontend/src/app/portal/deployment/create-edit-deployment/create-edit-deployment.scss
Labels: kind/enhancement, sig/frontend

#39 Feature/add english readme
  README-CN.md
  README.md
Labels: help wanted, kind/documentation

#44 Hotfix/no k8s namespace
  src/backend/controllers/kubernetes/namespace/namespace.go
Labels: approved, kind/bug

#45 renamed: PULL_REQUEST_TEMPLATE.md -> .github/PULL_REQUEST_TEMPLAT…
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation

#35 Fix the problem of creating a user verification in the background is not strict.
  src/frontend/src/app/admin/configmap/create-edit-configmap/create-edit-configmap.component.html
  src/frontend/src/app/admin/cronjob/create-edit-cronjob/create-edit-cronjob.component.html
  src/frontend/src/app/admin/daemonset/create-edit-daemonset/create-edit-daemonset.component.html
  src/frontend/src/app/admin/deployment/create-edit-deployment/create-edit-deployment.component.html
  src/frontend/src/app/admin/persistentvolumeclaim/create-edit-persistentvolumeclaim/create-edit-persistentvolumeclaim.component.html
  src/frontend/src/app/admin/secret/create-edit-secret/create-edit-secret.component.html
  src/frontend/src/app/admin/statefulset/create-edit-statefulset/create-edit-statefulset.component.html
  src/frontend/src/app/admin/user/create-edit-user/create-edit-user.component.html
  src/frontend/src/app/admin/user/create-edit-user/create-edit-user.component.ts
Labels: kind/enhancement, sig/frontend

#46 Feature/add english version architecture
  README-CN.md
  README.md
Labels: kind/documentation

#47 Feature/update kubernetes install
  hack/kubernetes/configmap.yaml
  hack/kubernetes/deployment.yaml
  src/backend/conf/app.conf
Labels: kind/enhancement, sig/install

#51 kubernetes install optimization
  hack/kubernetes/dependency/mysql.yaml
  hack/kubernetes/dependency/rabbitmq.yaml
  hack/kubernetes/wayne/configmap.yaml
  hack/kubernetes/wayne/deployment.yaml
  hack/kubernetes/wayne/service.yaml
Labels: kind/enhancement

#52 Hotfix/db error
  src/backend/models/notification.go
  src/backend/models/notification_log.go
Labels: kind/enhancement

#53 Feature/kubernetes example dependency resource adjust
  CHANGELOG.md
  bump.sh
  hack/kubernetes/dependency/mysql.yaml
  hack/kubernetes/dependency/rabbitmq.yaml
Labels: kind/enhancement

#58 frontend: Fix CronJob bug that opens advanced mode paste yaml error r…
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.ts
Labels: kind/bug, sig/frontend

#59 Feature/default config optimization
  src/backend/cmd/apiserver/apiserver.go
  src/backend/cmd/worker/worker.go
  src/backend/conf/app.conf
  src/backend/controllers/auth/authenticator.go
  src/backend/initial/db.go
Labels: kind/enhancement, sig/backend

#60 feature/modal-size-change-bug
  src/frontend/src/app/shared/modal-operate/modal-operate.component.ts
Labels: kind/bug, sig/frontend

#67 Feature/rename oauth2 qihoo to oauth2
  hack/kubernetes/wayne/configmap.yaml
  src/backend/conf/app.conf
  src/backend/controllers/config/baseconfig.go
  src/backend/oauth2/default.go
  src/backend/oauth2/oauth2.go
  src/frontend/src/app/shared/auth-module/sign-in/sign-in.component.html
  src/frontend/src/app/shared/auth-module/sign-in/sign-in.component.ts
Labels: kind/enhancement

#70 Feature/install optimization
  README-CN.md
  README.md
  docker-compose.yaml
  hack/kubernetes/wayne/configmap.yaml
  src/backend/conf/app.conf
  src/frontend/src/app/portal/base/base.component.ts
Labels: sig/install

#65 backend: db initial: add manual generate sql command
  Makefile
  src/backend/database/generatedata/main.go
  src/backend/database/syncdb.go
Labels: sig/install
