Repository Qihoo360/wayne, pull requests merged in 2019-03, with the labels that each got.

#326 Tpl edit add imagepullpolicy
  src/backend/controllers/kubernetes/pod/pod.go
  src/backend/resources/pod/pod.go
  src/backend/routers/commentsRouter_controllers_kubernetes_pod.go
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.html
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.html
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.html
  src/frontend/src/app/portal/pod-logging/pod-logging.component.html
  src/frontend/src/app/portal/pod-logging/pod-logging.component.ts
  src/frontend/src/app/portal/pod-terminal/pod-terminal.component.html
  src/frontend/src/app/portal/pod-terminal/pod-terminal.component.ts
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.html
  src/frontend/src/app/shared/client/v1/kubernetes/pod.ts
  src/frontend/src/app/shared/list-pod/list-pod.component.ts
Labels: kind/feature

#334 Feature/fix pvc create tpl save without access
  src/frontend/src/app/portal/ingress/create-edit-ingresstpl/create-edit-ingresstpl.component.html
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaimtpl/create-edit-persistentvolumeclaimtpl.component.ts
  src/frontend/src/app/shared/input/input.component.scss
Labels: kind/bug

#338 Kubernetes pod list add podIP filter
  src/backend/client/handler.go
  src/backend/resources/dataselector/const.go
  src/backend/resources/proxy/common.go
  src/backend/resources/proxy/factory.go
  src/backend/resources/proxy/proxy.go
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.html
Labels: kind/feature

#340 Add kubernetes resource all namespaces selection
  src/frontend/src/app/admin/kubernetes/configmap/kube-configmap.component.html
  src/frontend/src/app/admin/kubernetes/configmap/kube-configmap.component.ts
  src/frontend/src/app/admin/kubernetes/configmap/list-configmap/list-configmap.component.html
  src/frontend/src/app/admin/kubernetes/cronjob/kube-cronjob.component.html
  src/frontend/src/app/admin/kubernetes/cronjob/kube-cronjob.component.ts
  src/frontend/src/app/admin/kubernetes/cronjob/list-cronjob/list-cronjob.component.html
  src/frontend/src/app/admin/kubernetes/daemonset/kube-daemonset.component.html
  src/frontend/src/app/admin/kubernetes/daemonset/kube-daemonset.component.ts
  src/frontend/src/app/admin/kubernetes/daemonset/list-daemonset/list-daemonset.component.html
  src/frontend/src/app/admin/kubernetes/deployment/kube-deployment.component.html
  src/frontend/src/app/admin/kubernetes/deployment/kube-deployment.component.ts
  src/frontend/src/app/admin/kubernetes/deployment/list-deployment/list-deployment.component.html
  src/frontend/src/app/admin/kubernetes/endpoint/kube-endpoint.component.html
  src/frontend/src/app/admin/kubernetes/endpoint/kube-endpoint.component.ts
  src/frontend/src/app/admin/kubernetes/endpoint/list-endpoint/list-endpoint.component.html
  src/frontend/src/app/admin/kubernetes/hpa/kube-hpa.component.html
  src/frontend/src/app/admin/kubernetes/hpa/kube-hpa.component.ts
  src/frontend/src/app/admin/kubernetes/hpa/list-hpa/list-hpa.component.html
  src/frontend/src/app/admin/kubernetes/ingress/kube-ingress.component.html
  src/frontend/src/app/admin/kubernetes/ingress/kube-ingress.component.ts
  src/frontend/src/app/admin/kubernetes/ingress/list-ingress/list-ingress.component.html
  src/frontend/src/app/admin/kubernetes/job/kube-job.component.html
  src/frontend/src/app/admin/kubernetes/job/kube-job.component.ts
  src/frontend/src/app/admin/kubernetes/job/list-job/list-job.component.html
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.component.html
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.component.ts
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.html
  src/frontend/src/app/admin/kubernetes/pvc/kube-pvc.component.html
  src/frontend/src/app/admin/kubernetes/pvc/kube-pvc.component.ts
  src/frontend/src/app/admin/kubernetes/pvc/list-pvc/list-pvc.component.html
  src/frontend/src/app/admin/kubernetes/replicaset/kube-replicaset.component.html
  src/frontend/src/app/admin/kubernetes/replicaset/kube-replicaset.component.ts
  src/frontend/src/app/admin/kubernetes/replicaset/list-replicaset/list-replicaset.component.html
  src/frontend/src/app/admin/kubernetes/role/kube-role.component.html
  src/frontend/src/app/admin/kubernetes/role/kube-role.component.ts
  src/frontend/src/app/admin/kubernetes/role/list-role/list-role.component.html
  src/frontend/src/app/admin/kubernetes/rolebinding/kube-rolebinding.component.html
  src/frontend/src/app/admin/kubernetes/rolebinding/kube-rolebinding.component.ts
  src/frontend/src/app/admin/kubernetes/rolebinding/list-rolebinding/list-rolebinding.component.html
  src/frontend/src/app/admin/kubernetes/secret/kube-secret.component.html
  src/frontend/src/app/admin/kubernetes/secret/kube-secret.component.ts
  src/frontend/src/app/admin/kubernetes/secret/list-secret/list-secret.component.html
  src/frontend/src/app/admin/kubernetes/service/kube-service.component.html
  src/frontend/src/app/admin/kubernetes/service/kube-service.component.ts
  src/frontend/src/app/admin/kubernetes/service/list-service/list-service.component.html
  src/frontend/src/app/admin/kubernetes/serviceaccount/kube-serviceaccount.component.html
  src/frontend/src/app/admin/kubernetes/serviceaccount/kube-serviceaccount.component.ts
  src/frontend/src/app/admin/kubernetes/serviceaccount/list-serviceaccount/list-serviceaccount.component.html
  src/frontend/src/app/admin/kubernetes/statefulset/kube-statefulset.component.html
  src/frontend/src/app/admin/kubernetes/statefulset/kube-statefulset.component.ts
  src/frontend/src/app/admin/kubernetes/statefulset/list-statefulset/list-statefulset.component.html
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-resource.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature, status/done

#343 Kubernetes pod add nodeName filter
  src/backend/resources/dataselector/const.go
  src/backend/resources/proxy/common.go
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.html
Labels: kind/feature, status/done

#344 Fix inaccurate resource statistics
  src/backend/controllers/kubernetes/deployment/deployment.go
  src/backend/controllers/kubernetes/namespace/namespace.go
  src/backend/controllers/kubernetes/statefulset/statefulset.go
  src/backend/resources/deployment/deployment.go
  src/backend/resources/namespace/namespace.go
  src/backend/resources/statefulset/statefulset.go
  src/frontend/src/app/shared/client/v1/kubernetes/namespace.ts
Labels: kind/bug

#345 Fix endpoints update error
  src/backend/resources/deployment/deployment.go
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-resource.ts
Labels: kind/bug

#346 Fix deployment envs lost
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.html
Labels: kind/bug

#347 Update namespace model add kubenamespace field
  .travis.yml
  src/backend/controllers/common/deployment.go
  src/backend/controllers/kubernetes/cronjob/cronjob.go
  src/backend/controllers/kubernetes/cronjob/pre_deploy.go
  src/backend/controllers/kubernetes/daemonset/pre_deploy.go
  src/backend/controllers/kubernetes/deployment/deployment.go
  src/backend/controllers/kubernetes/namespace/namespace.go
  src/backend/controllers/kubernetes/statefulset/pre_deploy.go
  src/backend/controllers/kubernetes/statefulset/statefulset.go
  src/backend/controllers/openapi/deployment.go
  src/backend/database/migrations/v1.5_v1.6/ddl.sql
  src/backend/models/namespace.go
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.html
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.ts
  src/frontend/src/app/admin/namespace/list-namespace/list-namespace.component.html
  src/frontend/src/app/admin/namespace/list-namespace/list-namespace.component.ts
  src/frontend/src/app/shared/auth/cache.service.ts
  src/frontend/src/app/shared/model/v1/namespace.ts
Labels: kind/enhancement

#348 Update db migration workflow
  src/backend/database/migrations/20190312_154209_v1_6.go
  src/backend/database/migrations/v1.1/ddl.sql
  src/backend/database/migrations/v1.1/dml.sql
  src/backend/database/migrations/v1.3/ddl.sql
  src/backend/database/migrations/v1.3/dml.sql
  src/backend/database/migrations/v1.5_v1.6/ddl.sql
Labels: kind/enhancement

#350 Update README-CN.md
  README-CN.md
Labels: kind/bug

#352 Fix deployment and statefulset depoy panic
  src/backend/resources/deployment/deployment.go
  src/backend/resources/statefulset/statefulset.go
Labels: kind/bug

#354 Template edit form support Toggle info
  src/frontend/src/app/portal/autoscale/create-edit-autoscaletpl/create-edit-autoscaletpl.component.html
  src/frontend/src/app/portal/base/base.component.html
  src/frontend/src/app/portal/base/base.component.ts
  src/frontend/src/app/portal/configmap/create-edit-configmaptpl/create-edit-configmaptpl.component.html
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.html
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.html
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.html
  src/frontend/src/app/portal/ingress/create-edit-ingresstpl/create-edit-ingresstpl.component.html
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaimtpl/create-edit-persistentvolumeclaimtpl.component.html
  src/frontend/src/app/portal/secret/create-edit-secrettpl/create-edit-secrettpl.component.html
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.html
  src/frontend/src/app/shared/box/box.component.scss
  src/frontend/src/app/shared/box/box.component.ts
  src/frontend/src/app/shared/collapse/collapse.component.html
  src/frontend/src/app/shared/collapse/collapse.component.scss
  src/frontend/src/app/shared/collapse/collapse.component.ts
  src/frontend/src/app/shared/collapse/collapse.module.ts
  src/frontend/src/app/shared/shared.module.ts
  src/frontend/src/component/tpl.scss
  src/frontend/src/styles.scss
Labels: kind/feature, sig/frontend

#364 Admin kubernetes cluster add cache
  src/backend/bee.json
  src/backend/controllers/auth/authenticator.go
  src/backend/database/initial/data.go
  src/frontend/src/app/admin/kubernetes/node/nodes.component.html
  src/frontend/src/app/admin/kubernetes/node/nodes.component.ts
  src/frontend/src/app/admin/kubernetes/persistentvolume/persistentvolume.component.html
  src/frontend/src/app/admin/kubernetes/persistentvolume/persistentvolume.component.ts
  src/frontend/src/app/portal/autoscale/publish-tpl/publish-tpl.component.ts
  src/frontend/src/app/portal/deployment/publish-tpl/publish-tpl.component.ts
  src/frontend/src/app/portal/ingress/publish-tpl/publish-tpl.component.ts
  src/frontend/src/app/shared/auth-module/sign-in/sign-in.component.scss
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-resource.ts
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-unnamespaced-resource.ts
  src/frontend/src/app/shared/base/resource/publish-template.ts
  src/frontend/src/app/shared/sidenav.const.ts
Labels: kind/feature

#368 backend:Fix models user GetUserByName method
  src/backend/models/user.go
Labels: question

#372 Add template default values
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.html
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.ts
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.html
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.ts
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.ts
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.ts
  src/frontend/src/app/shared/default-models/cronjob.const.ts
Labels: kind/enhancement

#373 Pod list api default order by names
  src/backend/resources/pod/pod.go
Labels: kind/enhancement

#363 future: support eks image
  Dockerfile
  hack/build/base/Dockerfile
Labels: kind/feature

#375 Ingress template optimization
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.html
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.ts
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.html
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.ts
  src/frontend/src/app/portal/ingress/create-edit-ingresstpl/create-edit-ingresstpl.component.html
  src/frontend/src/app/portal/ingress/create-edit-ingresstpl/create-edit-ingresstpl.component.ts
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.html
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.ts
  src/frontend/src/app/shared/model/v1/kubernetes/ingress.ts
Labels: kind/enhancement

#378 Openapi add get_pod_list
  src/backend/controllers/kubernetes/pod/pod.go
  src/backend/controllers/openapi/openapi.go
  src/backend/controllers/openapi/pod.go
  src/backend/resources/common/common.go
  src/backend/resources/pod/pod.go
  src/backend/routers/commentsRouter_controllers_kubernetes_pod.go
  src/backend/routers/commentsRouter_controllers_openapi.go
  src/backend/swagger/openapi.swagger.json
Labels: kind/feature

#379 Fix template diff display error.
  src/frontend/src/app/shared/diff/diff.service.ts
Labels: kind/bug

#382 Portal template remove template initialDelaySeconds required
  src/backend/models/user.go
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.html
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.html
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaimtpl/create-edit-persistentvolumeclaimtpl.component.html
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaimtpl/create-edit-persistentvolumeclaimtpl.component.ts
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaimtpl/create-edit-persistentvolumeclaimtpl.scss
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.html
Labels: kind/bug
