Repository Qihoo360/wayne, pull requests merged in 2019-02, with the labels that each got.

#251 Admin route link optimization
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.component.ts
  src/frontend/src/app/admin/app/app.component.html
  src/frontend/src/app/admin/app/app.component.ts
  src/frontend/src/app/admin/app/list-app/list-app.component.html
  src/frontend/src/app/admin/app/list-app/list-app.component.ts
  src/frontend/src/app/admin/autoscale/create-edit-autoscale/create-edit-autoscale.component.ts
  src/frontend/src/app/admin/configmap/list-configmap/list-configmap.component.ts
  src/frontend/src/app/admin/configmaptpl/configmaptpl.component.ts
  src/frontend/src/app/admin/cronjob/list-cronjob/list-cronjob.component.ts
  src/frontend/src/app/admin/cronjobtpl/cronjobtpl.component.html
  src/frontend/src/app/admin/cronjobtpl/cronjobtpl.component.ts
  src/frontend/src/app/admin/daemonset/list-daemonset/list-daemonset.component.html
  src/frontend/src/app/admin/daemonset/list-daemonset/list-daemonset.component.ts
  src/frontend/src/app/admin/daemonsettpl/daemonsettpl.component.ts
  src/frontend/src/app/admin/deployment/list-deployment/list-deployment.component.ts
  src/frontend/src/app/admin/deploymenttpl/deploymenttpl.component.ts
  src/frontend/src/app/admin/ingress/list-ingress/list-ingress.component.ts
  src/frontend/src/app/admin/ingresstpl/ingresstpl.component.ts
  src/frontend/src/app/admin/persistentvolumeclaim/list-persistentvolumeclaim/list-persistentvolumeclaim.component.html
  src/frontend/src/app/admin/persistentvolumeclaim/list-persistentvolumeclaim/list-persistentvolumeclaim.component.ts
  src/frontend/src/app/admin/persistentvolumeclaimtpl/persistentvolumeclaimtpl.component.ts
  src/frontend/src/app/admin/secret/list-secret/list-secret.component.ts
  src/frontend/src/app/admin/secrettpl/secrettpl.component.ts
  src/frontend/src/app/admin/statefulset/list-statefulset/list-statefulset.component.html
  src/frontend/src/app/admin/statefulset/list-statefulset/list-statefulset.component.ts
  src/frontend/src/app/admin/statefulsettpl/statefulsettpl.component.ts
  src/frontend/src/app/shared/base/admin-resource/create-edit-resource.ts
  src/frontend/src/app/shared/base/admin-resource/list-resource.ts
  src/frontend/src/app/shared/base/admin-resource/resource-template.ts
  src/frontend/src/app/shared/base/admin-resource/resource.ts
  src/frontend/src/app/shared/client/v1/app.service.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: sig/frontend

#254 Feature/add kubernetes pod resource
  src/backend/controllers/base/parambuilder.go
  src/backend/controllers/kubernetes/proxy/proxy.go
  src/backend/resources/proxy/proxy.go
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.module.ts
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.component.html
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.component.ts
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.module.ts
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.html
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.ts
  src/frontend/src/app/admin/reportform/overview/overview.component.html
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/app/shared/ace-editor/ace-editor.component.html
  src/frontend/src/app/shared/ace-editor/ace-editor.component.ts
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-list-resource.ts
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-resource.ts
  src/frontend/src/app/shared/base/kubernetes/kubernetes-resource.ts
  src/frontend/src/app/shared/client/v1/kubernetes/common.ts
  src/frontend/src/app/shared/client/v1/kubernetes/kubernetes.ts
  src/frontend/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
  src/frontend/src/app/shared/confirmation-dialog/confirmation-message.ts
  src/frontend/src/app/shared/confirmation-dialog/confirmation-state-message.ts
  src/frontend/src/app/shared/deletion-dialog/deletion-dialog.component.html
  src/frontend/src/app/shared/deletion-dialog/deletion-dialog.component.scss
  src/frontend/src/app/shared/deletion-dialog/deletion-dialog.component.ts
  src/frontend/src/app/shared/deletion-dialog/deletion-dialog.module.ts
  src/frontend/src/app/shared/model/v1/kubernetes/kubepod.ts
  src/frontend/src/app/shared/shared.const.ts
  src/frontend/src/app/shared/tpl-detail/tpl-detail.component.html
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature, sig/backend, sig/frontend

#255 Add kubernetes service and endpoint resource
  src/backend/resources/common/common.go
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.module.ts
  src/frontend/src/app/admin/kubernetes/endpoint/kube-endpoint.component.html
  src/frontend/src/app/admin/kubernetes/endpoint/kube-endpoint.component.ts
  src/frontend/src/app/admin/kubernetes/endpoint/kube-endpoint.module.ts
  src/frontend/src/app/admin/kubernetes/endpoint/list-endpoint/list-endpoint.component.html
  src/frontend/src/app/admin/kubernetes/endpoint/list-endpoint/list-endpoint.component.ts
  src/frontend/src/app/admin/kubernetes/service/kube-service.component.html
  src/frontend/src/app/admin/kubernetes/service/kube-service.component.ts
  src/frontend/src/app/admin/kubernetes/service/kube-service.module.ts
  src/frontend/src/app/admin/kubernetes/service/list-service/list-service.component.html
  src/frontend/src/app/admin/kubernetes/service/list-service/list-service.component.ts
  src/frontend/src/app/admin/kubernetes/service/migration/migration.component.html
  src/frontend/src/app/admin/kubernetes/service/migration/migration.component.ts
  src/frontend/src/app/admin/kubernetes/service/service-dg-row-detail/service-dg-row-detail.component.html
  src/frontend/src/app/admin/kubernetes/service/service-dg-row-detail/service-dg-row-detail.component.ts
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-list-resource.ts
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-resource.ts
  src/frontend/src/app/shared/base/kubernetes-namespaced/migration-resource.ts
  src/frontend/src/app/shared/default-models/kube-resource.const.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#237 Feature/openapi upgrade deployment
  src/backend/controllers/openapi/deployment.go
Labels: sig/backend

#258 Fix get pod info API bug that label should be a key not a map
  src/backend/controllers/openapi/pod.go
  src/backend/resources/pod/pod.go
Labels: kind/bug

#261 Fix log detail error
  src/frontend/src/app/portal/pod-logging/pod-logging.component.html
  src/frontend/src/app/shared/client/v1/kubernetes/log.ts
Labels: kind/bug

#266 Fix portal configmap get status error
  src/frontend/src/app/portal/configmap/configmap.component.ts
Labels: kind/bug

#270 Different resource states by label of different colors
  src/frontend/src/app/portal/cronjob/cronjob.module.ts
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.html
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.ts
  src/frontend/src/app/portal/cronjob/list-pod/list-pod.component.html
  src/frontend/src/app/portal/cronjob/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/cronjob/list-pod/list-pod.scss
  src/frontend/src/app/portal/daemonset/daemonset.module.ts
  src/frontend/src/app/portal/daemonset/list-daemonset/list-daemonset.component.html
  src/frontend/src/app/portal/daemonset/list-daemonset/list-daemonset.component.ts
  src/frontend/src/app/portal/daemonset/list-pod/inventory.ts
  src/frontend/src/app/portal/daemonset/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/deployment/deployment.module.ts
  src/frontend/src/app/portal/deployment/list-deployment/list-deployment.component.html
  src/frontend/src/app/portal/deployment/list-deployment/list-deployment.component.ts
  src/frontend/src/app/portal/deployment/list-pod/inventory.ts
  src/frontend/src/app/portal/deployment/list-pod/list-pod.component.html
  src/frontend/src/app/portal/deployment/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/deployment/list-pod/list-pod.scss
  src/frontend/src/app/portal/statefulset/list-pod/inventory.ts
  src/frontend/src/app/portal/statefulset/list-pod/list-pod.component.html
  src/frontend/src/app/portal/statefulset/list-pod/list-pod.scss
  src/frontend/src/app/portal/statefulset/list-statefulset/list-statefulset.component.html
  src/frontend/src/app/portal/statefulset/list-statefulset/list-statefulset.component.ts
  src/frontend/src/app/portal/statefulset/statefulset.module.ts
  src/frontend/src/app/shared/list-pod/inventory.ts
  src/frontend/src/app/shared/list-pod/list-pod.component.html
  src/frontend/src/app/shared/list-pod/list-pod.component.ts
  src/frontend/src/app/shared/list-pod/list-pod.scss
  src/frontend/src/app/shared/shared.module.ts
Labels: kind/enhancement

#272 Fix pod log container i18 error
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/bug

#275 Secret template support set type
  src/frontend/src/app/portal/secret/create-edit-secrettpl/create-edit-secrettpl.component.html
  src/frontend/src/app/portal/secret/create-edit-secrettpl/create-edit-secrettpl.component.ts
Labels: kind/feature

#278 Fix pod list create time ref error
  src/backend/resources/pod/pod.go
Labels: kind/bug

#274 增加集群和命名空间级别自定义注解
  src/backend/controllers/common/ingress.go
  src/backend/controllers/common/service.go
  src/backend/controllers/kubernetes/deployment/deployment.go
  src/backend/controllers/kubernetes/ingress/ingress.go
  src/backend/controllers/kubernetes/service/service.go
  src/backend/models/cluster.go
  src/backend/models/namespace.go
Labels: kind/feature

#282 Add kubernetes statefulset resource
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.module.ts
  src/frontend/src/app/admin/kubernetes/statefulset/kube-statefulset.component.html
  src/frontend/src/app/admin/kubernetes/statefulset/kube-statefulset.component.ts
  src/frontend/src/app/admin/kubernetes/statefulset/kube-statefulset.module.ts
  src/frontend/src/app/admin/kubernetes/statefulset/list-statefulset/list-statefulset.component.html
  src/frontend/src/app/admin/kubernetes/statefulset/list-statefulset/list-statefulset.component.ts
  src/frontend/src/app/admin/kubernetes/statefulset/migration/migration.component.html
  src/frontend/src/app/admin/kubernetes/statefulset/migration/migration.component.ts
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/app/shared/base/kubernetes-namespaced/kubernetes-namespaced-resource.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#283 Fix create or clone configtpl url redirect error
  src/frontend/src/app/portal/configmap/configmap.component.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/bug

#285 Add kubernetes daemonset resource
  src/backend/controllers/kubernetes/service/service.go
  src/backend/models/namespace.go
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.module.ts
  src/frontend/src/app/admin/kubernetes/daemonset/kube-daemonset.component.html
  src/frontend/src/app/admin/kubernetes/daemonset/kube-daemonset.component.ts
  src/frontend/src/app/admin/kubernetes/daemonset/kube-daemonset.module.ts
  src/frontend/src/app/admin/kubernetes/daemonset/list-daemonset/list-daemonset.component.html
  src/frontend/src/app/admin/kubernetes/daemonset/list-daemonset/list-daemonset.component.ts
  src/frontend/src/app/admin/kubernetes/daemonset/migration/migration.component.html
  src/frontend/src/app/admin/kubernetes/daemonset/migration/migration.component.ts
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#287 Kubernetes cronjob and job support
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.module.ts
  src/frontend/src/app/admin/kubernetes/cronjob/kube-cronjob.component.html
  src/frontend/src/app/admin/kubernetes/cronjob/kube-cronjob.component.ts
  src/frontend/src/app/admin/kubernetes/cronjob/kube-cronjob.module.ts
  src/frontend/src/app/admin/kubernetes/cronjob/list-cronjob/list-cronjob.component.html
  src/frontend/src/app/admin/kubernetes/cronjob/list-cronjob/list-cronjob.component.ts
  src/frontend/src/app/admin/kubernetes/cronjob/migration/migration.component.html
  src/frontend/src/app/admin/kubernetes/cronjob/migration/migration.component.ts
  src/frontend/src/app/admin/kubernetes/job/kube-job.component.html
  src/frontend/src/app/admin/kubernetes/job/kube-job.component.ts
  src/frontend/src/app/admin/kubernetes/job/kube-job.module.ts
  src/frontend/src/app/admin/kubernetes/job/list-job/list-job.component.html
  src/frontend/src/app/admin/kubernetes/job/list-job/list-job.component.ts
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/app/portal/cronjob/cronjob.component.html
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.html
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#293 Add kubernetes hpa support
  src/frontend/src/app/admin/admin-routing.module.ts
  src/frontend/src/app/admin/admin.module.ts
  src/frontend/src/app/admin/kubernetes/hpa/kube-hpa.component.html
  src/frontend/src/app/admin/kubernetes/hpa/kube-hpa.component.ts
  src/frontend/src/app/admin/kubernetes/hpa/kube-hpa.module.ts
  src/frontend/src/app/admin/kubernetes/hpa/list-hpa/list-hpa.component.html
  src/frontend/src/app/admin/kubernetes/hpa/list-hpa/list-hpa.component.ts
  src/frontend/src/app/admin/kubernetes/hpa/migration/migration.component.html
  src/frontend/src/app/admin/kubernetes/hpa/migration/migration.component.ts
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#292 fix pagechange invalid
  src/frontend/lang.js
  src/frontend/src/app/shared/paginate/paginate.component.ts
Labels: kind/bug

#298 Add Kubernetes pod enter container action
  src/backend/controllers/kubernetes/pod/pod.go
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.component.html
  src/frontend/src/app/admin/kubernetes/pod/kube-pod.component.ts
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.html
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.ts
  src/frontend/src/app/shared/list-pod/list-pod.component.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#297 fix edit template metadata miss adjust
  src/frontend/src/app/portal/cronjob/create-edit-cronjob/create-edit-cronjob.component.ts
  src/frontend/src/app/portal/deployment/create-edit-deployment/create-edit-deployment.component.ts
  src/frontend/src/app/portal/statefulset/create-edit-statefulset/create-edit-statefulset.component.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/bug

#295 Add annotations to namespace in backend page
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.html
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.ts
  src/frontend/src/app/shared/model/v1/namespace.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/enhancement, status/done

#301 fix when exchange from table to json can not add updated data
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.html
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.ts
Labels: kind/bug, sig/frontend, status/done

#306 Fix list pvs status error
  src/frontend/src/app/portal/persistentvolumeclaim/list-persistentvolumeclaim/list-persistentvolumeclaim.component.ts
Labels: kind/bug

#305 admin sidenav url change location
  src/frontend/src/app/admin/sidenav/sidenav.component.html
  src/frontend/src/app/admin/sidenav/sidenav.component.ts
  src/frontend/src/app/shared/base/side-nav/side-nav-expand.ts
  src/frontend/src/app/shared/client/v1/sidenav.service.ts
  src/frontend/src/app/shared/shared.module.ts
  src/frontend/src/app/shared/sidenav.const.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#308 Container template support add command and args
  src/frontend/src/app/admin/namespace/create-edit-namespace/create-edit-namespace.component.html
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.html
  src/frontend/src/app/portal/cronjob/create-edit-cronjobtpl/create-edit-cronjobtpl.component.ts
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.html
  src/frontend/src/app/portal/daemonset/create-edit-daemonsettpl/create-edit-daemonsettpl.component.ts
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.html
  src/frontend/src/app/portal/deployment/create-edit-deploymenttpl/create-edit-deploymenttpl.component.ts
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.html
  src/frontend/src/app/portal/statefulset/create-edit-statefulsettpl/create-edit-statefulsettpl.component.ts
  src/frontend/src/app/shared/base/container/container-tpl.ts
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature, sig/frontend

#315 Deploy status optimization
  src/backend/controllers/kubernetes/pod/pod.go
  src/backend/resources/pod/common.go
  src/backend/resources/pod/pod.go
  src/backend/routers/commentsRouter_controllers_kubernetes_pod.go
  src/frontend/src/app/admin/kubernetes/pod/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.html
  src/frontend/src/app/portal/cronjob/list-job/list-job.component.ts
  src/frontend/src/app/portal/daemonset/list-daemonset/list-daemonset.component.html
  src/frontend/src/app/portal/daemonset/list-daemonset/list-daemonset.component.ts
  src/frontend/src/app/portal/deployment/list-deployment/list-deployment.component.html
  src/frontend/src/app/portal/deployment/list-deployment/list-deployment.component.ts
  src/frontend/src/app/portal/statefulset/list-statefulset/list-statefulset.component.html
  src/frontend/src/app/portal/statefulset/list-statefulset/list-statefulset.component.ts
  src/frontend/src/app/shared/client/v1/kubernetes/pod.ts
  src/frontend/src/app/shared/list-pod/inventory.ts
  src/frontend/src/app/shared/list-pod/list-pod.component.html
  src/frontend/src/app/shared/list-pod/list-pod.component.ts
  src/frontend/src/app/shared/model/v1/available-port.ts
  src/frontend/src/app/shared/utils.ts
Labels: kind/enhancement, status/done

#319 create-edit component rebuild
  src/frontend/src/app/portal/autoscale/create-edit-autoscale/create-edit-autoscale.component.html
  src/frontend/src/app/portal/configmap/configmap.component.ts
  src/frontend/src/app/portal/configmap/create-edit-configmap/create-edit-configmap.component.html
  src/frontend/src/app/portal/configmap/create-edit-configmap/create-edit-configmap.component.ts
  src/frontend/src/app/portal/cronjob/create-edit-cronjob/create-edit-cronjob.component.html
  src/frontend/src/app/portal/cronjob/create-edit-cronjob/create-edit-cronjob.component.ts
  src/frontend/src/app/portal/cronjob/cronjob.component.ts
  src/frontend/src/app/portal/cronjob/publish-tpl/publish-tpl.component.ts
  src/frontend/src/app/portal/daemonset/create-edit-daemonset/create-edit-daemonset.component.html
  src/frontend/src/app/portal/daemonset/create-edit-daemonset/create-edit-daemonset.component.ts
  src/frontend/src/app/portal/daemonset/daemonset.component.ts
  src/frontend/src/app/portal/deployment/create-edit-deployment/create-edit-deployment.component.html
  src/frontend/src/app/portal/deployment/create-edit-deployment/create-edit-deployment.component.ts
  src/frontend/src/app/portal/deployment/deployment.component.ts
  src/frontend/src/app/portal/deployment/publish-tpl/publish-tpl.component.ts
  src/frontend/src/app/portal/ingress/create-edit-ingress/create-edit-ingress.component.html
  src/frontend/src/app/portal/ingress/create-edit-ingress/create-edit-ingress.component.ts
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaim/create-edit-persistentvolumeclaim.component.html
  src/frontend/src/app/portal/persistentvolumeclaim/create-edit-persistentvolumeclaim/create-edit-persistentvolumeclaim.component.ts
  src/frontend/src/app/portal/persistentvolumeclaim/persistentvolumeclaim.component.ts
  src/frontend/src/app/portal/secret/create-edit-secret/create-edit-secret.component.html
  src/frontend/src/app/portal/secret/create-edit-secret/create-edit-secret.component.ts
  src/frontend/src/app/portal/secret/secret.component.ts
  src/frontend/src/app/portal/statefulset/create-edit-statefulset/create-edit-statefulset.component.html
  src/frontend/src/app/portal/statefulset/create-edit-statefulset/create-edit-statefulset.component.ts
  src/frontend/src/app/portal/statefulset/statefulset.component.ts
  src/frontend/src/app/shared/base/resource/create-edit-limit-resource.ts
  src/frontend/src/app/shared/base/resource/create-edit-resource.ts
  src/frontend/src/app/shared/model/v1/cluster.ts
  src/frontend/src/app/shared/model/v1/cronjob.ts
  src/frontend/src/app/shared/model/v1/deployment.ts
Labels: kind/enhancement, sig/frontend

#320 frontend: remove modal padding
  src/frontend/src/styles.scss
Labels: kind/enhancement

#322 Fix worker lost connection will fall into an infinite loop
  src/backend/cmd/worker/worker.go
  src/backend/workers/workers.go
Labels: kind/bug

#323 confirm height 100 screen
  src/frontend/src/styles.scss
Labels: kind/enhancement
