Repository Qihoo360/wayne, pull requests merged in 2019-01, with the labels that each got.

#192 Add Node resource statistics
  src/backend/client/client.go
  src/backend/controllers/kubernetes/deployment/deployment.go
  src/backend/controllers/kubernetes/namespace/namespace.go
  src/backend/controllers/kubernetes/statefulset/statefulset.go
  src/backend/resources/common/util.go
  src/backend/resources/namespace/namespace.go
  src/backend/resources/node/node.go
  src/backend/resources/pod/pod.go
  src/backend/routers/commentsRouter_controllers_ingress.go
  src/frontend/src/app/admin/kubernetes/node/nodes.component.ts
Labels: kind/feature

#169 Feature: add fetch ingress list and ingress detail from k8s cluster api to backend
  src/backend/controllers/kubernetes/ingress/ingress.go
  src/backend/resources/ingress/common.go
  src/backend/resources/ingress/ingress.go
  src/backend/resources/ingress/list.go
  src/backend/routers/commentsRouter_controllers_kubernetes_ingress.go
Labels: kind/feature, sig/backend

#191 backend statefulset daemonset i18n
  src/frontend/src/app/admin/daemonset/create-edit-daemonset/create-edit-daemonset.component.html
  src/frontend/src/app/admin/daemonset/daemonset.component.html
  src/frontend/src/app/admin/daemonset/trash-daemonset/trash-daemonset.component.html
  src/frontend/src/app/admin/statefulset/create-edit-statefulset/create-edit-statefulset.component.html
  src/frontend/src/app/admin/statefulset/statefulset.component.html
  src/frontend/src/app/admin/statefulset/trash-statefulset/trash-statefulset.component.html
  src/frontend/src/app/portal/statefulset/create-edit-statefulset/create-edit-statefulset.component.html
  src/frontend/src/assets/i18n/zh-Hans.json
Labels: kind/feature

#196 Client cache optimization
  src/backend/client/cache.go
  src/backend/client/client.go
  src/backend/cmd/apiserver/apiserver.go
  src/backend/controllers/kubernetes/daemonset/daemonset.go
  src/backend/controllers/kubernetes/deployment/deployment.go
  src/backend/controllers/kubernetes/job/job.go
  src/backend/controllers/kubernetes/namespace/namespace.go
  src/backend/controllers/kubernetes/node/node.go
  src/backend/controllers/kubernetes/pod/pod.go
  src/backend/controllers/kubernetes/service/service.go
  src/backend/controllers/kubernetes/statefulset/statefulset.go
  src/backend/controllers/openapi/deployment.go
  src/backend/controllers/openapi/pod.go
  src/backend/initial/client.go
  src/backend/oauth2/oauth2.go
  src/backend/resources/daemonset/daemonset.go
  src/backend/resources/deployment/deployment.go
  src/backend/resources/deployment/list.go
  src/backend/resources/endpoint/endpoint.go
  src/backend/resources/event/event.go
  src/backend/resources/job/job.go
  src/backend/resources/node/node.go
  src/backend/resources/pod/pod.go
  src/backend/resources/service/detail.go
  src/backend/resources/statefulset/statefulset.go
  src/backend/util/maps/maps.go
Labels: kind/design, kind/enhancement

#204 Feature/client optimization
  src/backend/client/api/types.go
  src/backend/client/cache.go
  src/backend/client/client.go
  src/backend/client/clientfactory.go
  src/backend/client/handler.go
  src/backend/common/query.go
  src/backend/controllers/base/api.go
  src/backend/controllers/base/parambuilder.go
  src/backend/controllers/kubernetes/proxy/proxy.go
  src/backend/models/response/response.go
  src/backend/resources/common/common.go
  src/backend/resources/proxy/common.go
  src/backend/resources/proxy/proxy.go
  src/backend/routers/commentsRouter_controllers_kubernetes_proxy.go
  src/backend/routers/router.go
  src/frontend/src/app/shared/client/v1/kubernetes/common.ts
  src/frontend/src/app/shared/shared.const.ts
Labels: kind/design

#212 Fix kubernetes deployment switch cluster not reload namespaces
  src/frontend/src/app/admin/kubernetes/deployment/kube-deployment.component.html
  src/frontend/src/app/admin/kubernetes/deployment/kube-deployment.component.ts
  src/frontend/src/app/admin/kubernetes/deployment/migration/kube-migration-deployment.component.html
  src/frontend/src/app/shared/select/select.component.scss
Labels: kind/bug, sig/frontend

#215 Fix normal user create deployment error
  src/frontend/src/app/portal/deployment/create-edit-deployment/create-edit-deployment.component.html
Labels: kind/bug

#219 Fix Node resource statistics: limit to request
  src/backend/resources/common/util.go
  src/backend/resources/node/node.go
Labels: kind/bug

#239 frontend:fix error route in jump url
  src/frontend/src/app/portal/cronjob/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/daemonset/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/deployment/list-pod/list-pod.component.ts
  src/frontend/src/app/portal/pod-logging/pod-logging.component.ts
  src/frontend/src/app/portal/pod-terminal/pod-terminal.component.ts
  src/frontend/src/app/portal/statefulset/list-pod/list-pod.component.ts
Labels: kind/bug
